const TOOLS = [
  { id:'json', name:'JSON 格式化/验证', desc:'格式化、压缩、验证 JSON 数据，支持语法高亮', icon:'📋', cat:'数据格式', kw:['json','format','格式化','验证','validate'], page:'tools/json.html' },
  { id:'base64', name:'Base64 编解码', desc:'文本与 Base64 互相转换，支持文件编码', icon:'🔤', cat:'编码转换', kw:['base64','encode','decode','编码','解码'], page:'tools/base64.html' },
  { id:'regex', name:'正则表达式测试', desc:'实时测试正则，匹配高亮，常用正则模板', icon:'🎯', cat:'文本处理', kw:['regex','regexp','正则','regular','expression'], page:'tools/regex.html' },
  { id:'color', name:'颜色转换器', desc:'HEX / RGB / HSL / CMYK 互转，取色器', icon:'🎨', cat:'设计工具', kw:['color','颜色','hex','rgb','hsl','convert'], page:'tools/color.html' },
  { id:'url', name:'URL 编解码', desc:'URL 编码解码，参数解析，Query String 处理', icon:'🔗', cat:'编码转换', kw:['url','encode','decode','uri','component'], page:'tools/url.html' },
  { id:'timestamp', name:'时间戳转换', desc:'Unix 时间戳与日期互转，支持毫秒/秒', icon:'🕐', cat:'时间日期', kw:['timestamp','unix','date','时间戳','日期','epoch'], page:'tools/timestamp.html' },
  { id:'password', name:'密码生成器', desc:'自定义长度和字符集，评估密码强度', icon:'🔐', cat:'安全工具', kw:['password','generator','密码','生成','random'], page:'tools/password.html' },
  { id:'hash', name:'Hash 计算器', desc:'MD5 / SHA-1 / SHA-256 / SHA-512 哈希计算', icon:'🔑', cat:'安全工具', kw:['hash','md5','sha','sha256','sha512','加密'], page:'tools/hash.html' },
  { id:'jwt', name:'JWT 解码器', desc:'解析 JWT Token，查看 Header / Payload / Signature', icon:'🎟️', cat:'Web开发', kw:['jwt','token','json','web','token','decode'], page:'tools/jwt.html' },
  { id:'uuid', name:'UUID 生成器', desc:'批量生成 UUID v4，一键复制', icon:'🆔', cat:'开发工具', kw:['uuid','guid','unique','id','identifier'], page:'tools/uuid.html' },
  { id:'lorem', name:'Lorem Ipsum', desc:'生成占位文本，支持中文/英文/段落/单词', icon:'📝', cat:'文本处理', kw:['lorem','ipsum','placeholder','占位','文本'], page:'tools/lorem.html' },
  { id:'markdown', name:'Markdown 预览', desc:'实时 Markdown 渲染预览，支持 GitHub 风格', icon:'📄', cat:'文本处理', kw:['markdown','md','preview','previewer'], page:'tools/markdown.html' },
  { id:'css', name:'CSS 渐变生成器', desc:'可视化创建 CSS 渐变，实时预览代码', icon:'🌈', cat:'设计工具', kw:['css','gradient','渐变','background'], page:'tools/css-gradient.html' },
  { id:'cron', name:'Cron 表达式', desc:'Cron 表达式解析与生成，可视化编辑', icon:'⏰', cat:'开发工具', kw:['cron','schedule','定时','表达式','crontab'], page:'tools/cron.html' },
  { id:'diff', name:'文本对比', desc:'对比两段文本差异，逐行高亮显示', icon:'📊', cat:'文本处理', kw:['diff','compare','对比','比较','difference'], page:'tools/diff.html' },
  { id:'html', name:'HTML 实体编码', desc:'HTML 特殊字符转义与反转义', icon:'&amp;', cat:'编码转换', kw:['html','entity','encode','escape','实体'], page:'tools/html-entity.html' },
  { id:'number', name:'进制转换', desc:'二进制/八进制/十进制/十六进制互转', icon:'🔢', cat:'数学计算', kw:['number','base','binary','hex','octal','进制'], page:'tools/number-base.html' },
  { id:'qrcode', name:'二维码生成', desc:'输入文本或URL生成二维码，支持下载', icon:'📱', cat:'开发工具', kw:['qrcode','qr','二维码','barcode'], page:'tools/qrcode.html' },
  { id:'image', name:'图片压缩', desc:'在浏览器内压缩图片，无需上传服务器', icon:'🖼️', cat:'设计工具', kw:['image','compress','压缩','optimize','图片'], page:'tools/image-compress.html' },
  { id:'meta', name:'Meta 标签生成', desc:'生成 SEO 友好的 HTML Meta 标签', icon:'🏷️', cat:'Web开发', kw:['meta','tag','seo','og','open','graph'], page:'tools/meta-tag.html' },
];
